# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/udisks2-qt5.spec

# add or remove files that should be synced
synced_files:
    - rpm/udisks2-qt5.spec
    - .packit.yaml

upstream_package_name: udisks2-qt5
# downstream (Fedora) RPM package name
downstream_package_name: udisks2-qt5

actions:
  fix-spec-file: |
    bash -c "sed -i -r \"s/Version:(\s*)\S*/Version:\1${PACKIT_PROJECT_VERSION}/\" rpm/udisks2-qt5.spec"
